# http://materialdesignicons.com/cdn/7.4.47/

# Define icons used
font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: icon_font
    size: 36
    bpp: 4
    glyphs: [
      "\U000F1051",  # mdi-led-strip-variant
      "\U000F07D6",  # mdi-led-strip
      "\U000F0335",  # mdi-lightbulb
      "\U000F1A4C",  # mdi-lightbulb-night
      "\U000F06E8"   # mdi-lightbulb-on 
      ]

# Map icons to names
substitutions:
  ledstrip:       "\U000F1051"
  ledstrip2:      "\U000F07D6"
  lightbulb:      "\U000F0335"
  nightlight:     "\U000F1A4C"
  lightbulb-on:   "\U000F06E8"
