sensor:

  # Header Temperate
  - platform: homeassistant
    entity_id: sensor.karyna_clock_karina_room_temperature
    id: office_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(id(outdoor_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.hue_outdoor_motion_sensor_2_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(x)', '(int)round(id(office_temperature).state)' ]


  - platform: homeassistant
    entity_id: sensor.karyna_clock_karina_room_co2
    id: karina_room_co2
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d° / %d°"
            args: [ '(int)round(x)', '(int)round(id(office_temperature).state)' ]

  # Karina Room Humidity
  - platform: homeassistant
    entity_id: sensor.karyna_clock_karina_room_humidity
    id: karina_room_humidity
    on_value:
      - lvgl.table.update:
          id: sensor_table
          row: 1
          col: 1
          text:
            format: "%d%%"
            args: [ '(int)round(x)' ]

  # Karina Room Temperature
  - platform: homeassistant
    entity_id: sensor.karyna_clock_karina_room_temperature
    id: karina_room_temperature
    on_value:
      - lvgl.table.update:
          id: sensor_table
          row: 1
          col: 0
          text:
            format: "%d°"
            args: [ '(int)round(x)' ]

  # Karina Room CO2
  - platform: homeassistant
    entity_id: sensor.karyna_clock_karina_room_co2
    id: karina_room_co2
    on_value:
      - lvgl.table.update:
          id: sensor_table
          row: 1
          col: 2
          text:
            format: "%d ppm"
            args: [ '(int)round(x)' ]



