sensor:

  # Header Temperate
  - platform: homeassistant
    entity_id: sensor.karyna_clock_karina_room_temperature
    id: office_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(id(outdoor_temperature).state)', '(int)round(x)' ]

  - platform: homeassistant
    entity_id: sensor.hue_outdoor_motion_sensor_2_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%d째 / %d째"
            args: [ '(int)round(x)', '(int)round(id(office_temperature).state)' ]


binary_sensor:

  # Office Evening Scene
  - platform: homeassistant
    id: office_scene_evening
    entity_id: binary_sensor.office_scene_evening
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda return x;

